In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
!pip install imbalanced-learn==0.6.0

from imblearn.over_sampling import SMOTE


dataset = pd.read_excel("Dataset.xlsx")

X = dataset[['Perimeter' , 'Compactness']]
y = dataset.Class 



from sklearn.model_selection import train_test_split
XTrain, XTest, yTrain, yTest = train_test_split(X, y, test_size = 0.2, random_state = 0)


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
XTrain = sc.fit_transform(XTrain)
XTest = sc.transform(XTest)


print("Before OverSampling, counts of label '1': {}".format(sum(yTrain == 1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(yTrain == 0)))


# import SMOTE module from imblearn library
# pip install imblearn (if you don't have imblearn in your system)
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 2)
X_train_res, y_train_res = sm.fit_resample(XTrain, yTrain.ravel())


print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))


print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))


# training the kernel SVM model
from sklearn.svm import SVC # import SVC model
classifier = SVC(kernel = 'rbf', random_state = 0) # creat model's object
classifier.fit(X_train_res, y_train_res) # fits the model to the training data


# predicting the test set 
y_predict = classifier.predict(XTest)


from sklearn.metrics import confusion_matrix, accuracy_score
con_matrx = confusion_matrix(yTest, y_predict)
print(con_matrx)
accuracy_score(yTest, y_predict) 


Before OverSampling, counts of label '1': 0
Before OverSampling, counts of label '0': 0 

After OverSampling, the shape of train_X: (19677, 2)
After OverSampling, the shape of train_y: (19677,) 

After OverSampling, counts of label '1': 0
After OverSampling, counts of label '0': 0
[[189   0  53   0   1   2  10]
 [  0  92   0   0   0   0   0]
 [ 45   0 294   0   6   1   4]
 [  0   0   0 666   2  12  55]
 [  0   0  10   2 362   0  16]
 [  0   0   0   1   0 357  18]
 [  0   0   2  46   6  10 461]]


0.889092912229159

In [11]:
data = pd.read_excel("Kitap2.xlsx")
x = data[['Perimeter' , 'Compactness']]
Y = data.Class 

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 2)
x, Y = sm.fit_resample(x, Y.ravel())

# predicting the test set 
y_predict = classifier.predict(x)


from sklearn.metrics import confusion_matrix, accuracy_score
con_matrx = confusion_matrix(Y, y_predict)
print(con_matrx)
accuracy_score(Y, y_predict) 

[[10  0]
 [10  0]]


/Users/mumin/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


0.5